apiVersion: v1
kind: Pod
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  containers:
    - name: order-service
      image: order-service:0.1.0
      ports:
        - containerPort: 8080
